Repository daillywak/wak, pull requests merged in 2022-08, with the labels that each got.

#33 Feat: 캐릭터 스킬 백어택 판정, 스킬 강화
  Assets/Animation/Character/Attack.anim
  Assets/Animation/Character/Skill_Gal.anim
  Assets/Scenes/SampleScene.unity
  Assets/ScriptableObject/Character/Test 0.asset
  Assets/ScriptableObject/Character/Test 1.asset
  Assets/ScriptableObject/Character/Test 2.asset
  Assets/ScriptableObject/Character/Test 3.asset
  Assets/ScriptableObject/Character/Test 4.asset
  Assets/Scripts/Boss/BossCollider.cs
  Assets/Scripts/Boss/Wakgui/Wakgui.cs
  Assets/Scripts/Boss/Wakgui/Waves.cs
  Assets/Scripts/Character.cs
  Assets/Scripts/Manager/GameMng.cs
  Assets/Scripts/Manager/Scriptable/BossData.cs
  Assets/Scripts/Manager/Scriptable/CharacterData.cs
  Assets/Scripts/Manager/Scriptable/ItemData.cs
  Assets/Scripts/Manager/Scriptable/SkillData.cs
  Assets/Scripts/SetMapSize.cs
  Assets/Scripts/SetMapSize.cs.meta
  Assets/Scripts/UI/SkillUI.cs
  Assets/Scripts/UI/SkillUI.cs.meta
Labels: feature

#35 Feat: 보스 똥 애니메이션 & 전사 기본 공격 조절
  Assets/Animation/Boss/Wakgui/Poo/poo.controller
  Assets/Animation/Character/Attack.anim
  Assets/Prefab/Boss/Wakgui/Boss_Wakgui.prefab
  Assets/Prefab/Boss/Wakgui/poo.prefab
  Assets/Prefab/Boss/Wakgui/wave.prefab
  Assets/Prefab/UI/Character.prefab
  Assets/Scenes/SampleScene.unity
  Assets/Scripts/Boss/Wakgui/Poo.cs
  Assets/Scripts/Boss/Wakgui/Wakgui.cs
  ProjectSettings/TagManager.asset
Labels: feature

#42 Feat: 보스 왕따패턴 구현 (merge #41)
  Assets/Animation/Boss/Wakgui/Magic_circle/Magic_circle_GBR.anim
  Assets/Animation/Boss/Wakgui/Magic_circle/Magic_circle_GOR.anim
  Assets/Animation/Boss/Wakgui/Magic_circle/Magic_circle_OGB.anim
  Assets/Animation/Boss/Wakgui/Magic_circle/Magic_circle_ORG.anim
  Assets/Animation/Boss/Wakgui/Magic_circle/Magic_circle_RBG.anim
  Assets/Animation/Boss/Wakgui/Magic_circle/Magic_circle_ROB.anim
  Assets/Animation/Boss/Wakgui/Outcast/SafeZoneBlink.anim
  Assets/Animation/Boss/Wakgui/Outcast/SafeZoneBlink.anim.meta
  Assets/Animation/Boss/Wakgui/Outcast/Totem.anim
  Assets/Animation/Boss/Wakgui/Outcast/safe_zone.controller
  Assets/Animation/Boss/Wakgui/Outcast_Spawning.anim
  Assets/Animation/Boss/Wakgui/Wakgui.controller
  Assets/Prefab/Boss/Wakgui/Boss_Wakgui.prefab
  Assets/Prefab/Boss/Wakgui/Marble_outcast.prefab
  Assets/Prefab/Boss/Wakgui/Outcast_totem_rect.prefab
  Assets/Prefab/Boss/Wakgui/Outcast_totem_rect.prefab.meta
  Assets/Prefab/Boss/Wakgui/Outcast_totem_triangle.prefab
  Assets/Prefab/Boss/Wakgui/Outcast_totem_triangle.prefab.meta
  Assets/Prefab/Boss/Wakgui/Rect.prefab
  Assets/Prefab/Boss/Wakgui/Rect.prefab.meta
  Assets/Prefab/Boss/Wakgui/Triangle.prefab
  Assets/Prefab/Boss/Wakgui/Triangle.prefab.meta
  Assets/Scenes/SampleScene.unity
  Assets/ScriptableObject/Buff/DeBuff_SHIELD.asset
  Assets/Scripts/Boss/Wakgui/ChangeAction.cs
  Assets/Scripts/Boss/Wakgui/OutCast.cs
  Assets/Scripts/Boss/Wakgui/OutCast.cs.meta
  Assets/Scripts/Boss/Wakgui/Totem.cs
  Assets/Scripts/Boss/Wakgui/Totem.cs.meta
  Assets/Scripts/Boss/Wakgui/Wakgui.cs
  Assets/Scripts/Buff.cs
  Assets/Scripts/Character.cs
  Assets/Scripts/Manager/StateMng.cs
  ProjectSettings/TagManager.asset
Labels: feature

#44 Feat : 보스 왁귀 버그 수정
  Assets/Animation/Boss/Wakgui/roar.anim
  Assets/Animation/Boss/Wakgui/rush.anim
  Assets/Animation/Boss/Wakgui/slash.anim
  Assets/Animation/Boss/Wakgui/stap.anim
  Assets/Scripts/Boss/Wakgui/ChangeAction.cs
  Assets/Scripts/Boss/Wakgui/OutCast.cs
  Assets/Scripts/Boss/Wakgui/Totem.cs
  Assets/Scripts/Boss/Wakgui/Wakgui.cs
  Assets/Sprites/Esther/Viichan.psb.meta
Labels: feature

#54 Feat: inventory 방식 변경, 보스 패턴 1 무적 추가
  Assets/Fonts/숫자용_KoPub_돋움.asset
  Assets/Prefab/ItemSlot/Equip_Item/BatBT.prefab
  Assets/Scenes/SampleScene.unity
  Assets/ScriptableObject/Boss/Wakgui.asset
  Assets/ScriptableObject/Buff/Buff_GAL.asset
  Assets/Scripts/Boss/Boss.cs
  Assets/Scripts/Boss/BossBuff.cs
  Assets/Scripts/Boss/BossCollider.cs
  Assets/Scripts/Boss/Wakgui/Bullet.cs
  Assets/Scripts/Boss/Wakgui/ChangeAction.cs
  Assets/Scripts/Boss/Wakgui/Knife_portal.cs
  Assets/Scripts/Boss/Wakgui/Marble.cs
  Assets/Scripts/Boss/Wakgui/Poo.cs
  Assets/Scripts/Boss/Wakgui/Wakgui.cs
  Assets/Scripts/Boss/Wakgui/Waves.cs
  Assets/Scripts/Buff.cs
  Assets/Scripts/Character/Character.cs
  Assets/Scripts/Character/CharacterCollider.cs
  Assets/Scripts/Damage.cs
  Assets/Scripts/Manager/GameMng.cs
  Assets/Scripts/Manager/Scriptable/BaseMonsterData.cs
  Assets/Scripts/Manager/Scriptable/BaseMonsterData.cs.meta
  Assets/Scripts/Manager/Scriptable/BossData.cs
  Assets/Scripts/Manager/StateMng.cs
  Assets/Scripts/UI/Inventory/Inventory.cs
  Assets/Scripts/UI/Inventory/Slot.cs
Labels: duplicate, feature

#56 Feat: 배틀아이템 슬롯 지정 기능 추가 #55
  Assets/Prefab/Boss/chicken.prefab
  Assets/Prefab/Boss/chicken.prefab.meta
  Assets/Prefab/Character/Warrior.prefab
  Assets/Prefab/ItemSlot.meta
  Assets/Prefab/ItemSlot/Battle_Item.meta
  Assets/Prefab/ItemSlot/Battle_Item/CleanserBT.prefab
  Assets/Prefab/ItemSlot/Battle_Item/CleanserBT.prefab.meta
  Assets/Prefab/ItemSlot/Battle_Item/SpeedUpBT.prefab
  Assets/Prefab/ItemSlot/Battle_Item/SpeedUpBT.prefab.meta
  Assets/Prefab/ItemSlot/Consumable_Item.meta
  Assets/Prefab/ItemSlot/Consumable_Item/RedMushroomBT.prefab
  Assets/Prefab/ItemSlot/Consumable_Item/RedMushroomBT.prefab.meta
  Assets/Prefab/ItemSlot/Equip_Item.meta
  Assets/Prefab/ItemSlot/Equip_Item/BatBT.prefab
  Assets/Prefab/ItemSlot/Equip_Item/BroomBT.prefab
  Assets/Prefab/ItemSlot/Equip_Item/BroomBT.prefab.meta
  Assets/Prefab/ItemSlot/Equip_Item/CandyBT.prefab
  Assets/Prefab/ItemSlot/Equip_Item/CandyBT.prefab.meta
  Assets/Prefab/ItemSlot/Equip_Item/RoseBT.prefab
  Assets/Prefab/ItemSlot/Equip_Item/SanghyunBT.prefab
  Assets/Prefab/ItemSlot/Equip_Item/SanghyunBT.prefab.meta
  Assets/Prefab/ItemSlot/Equip_Item/StaffBT.prefab
  Assets/Prefab/ItemSlot/Equip_Item/StaffBT.prefab.meta
  Assets/Prefab/ItemSlot/Equip_Item/StickBT.prefab
  Assets/Prefab/ItemSlot/Equip_Item/StickBT.prefab.meta
  Assets/Prefab/ItemSlot/Equip_Item/SwordBT.prefab
  Assets/Prefab/ItemSlot/Equip_Item/SwordBT.prefab.meta
  Assets/Prefab/ItemSlot/Equip_Item/WakchoriBT.prefab
  Assets/Prefab/ItemSlot/Equip_Item/WakchoriBT.prefab.meta
  Assets/Prefab/ItemSlot/Equip_Item/WandBT.prefab
  Assets/Prefab/ItemSlot/Equip_Item/WandBT.prefab.meta
  Assets/Prefab/ItemSlot/Unuseful_Item.meta
  Assets/Prefab/UI/Skill.prefab
  Assets/Prefab/UI/SlotBT.prefab
  Assets/Prefab/UI/SlotBT.prefab.meta
  Assets/Scenes/SampleScene.unity
  Assets/Scripts/Boss/Boss.cs
  Assets/Scripts/Boss/BossCollider.cs
  Assets/Scripts/Boss/Wakgui/Wakgui.cs
  Assets/Scripts/Character/Character.cs
  Assets/Scripts/Character/CharacterCollider.cs
  Assets/Scripts/Item.cs
  Assets/Scripts/ItemObj.cs
  Assets/Scripts/ItemObj.cs.meta
  Assets/Scripts/Manager/Enum.cs
  Assets/Scripts/Manager/GameMng.cs
  Assets/Scripts/Manager/MCamera.cs
  Assets/Scripts/Manager/Scriptable/ItemData.cs
  Assets/Scripts/Manager/StateMng.cs
  Assets/Scripts/UI/Inventory/Inventory.cs
  Assets/Scripts/UI/Inventory/Slot.cs
  Assets/Sprites/Boss/chicken.meta
  Assets/Sprites/Boss/chicken/chicken.psb
  Assets/Sprites/Boss/chicken/chicken.psb.meta
Labels: feature

#58 Feat: 배틀 아이템 별 사용 기능 추가
  Assets/Fonts/숫자용_KoPub_돋움.asset
  Assets/Scenes/SampleScene.unity
  Assets/ScriptableObject/Item/BATTLE_ITEM/Cleanser.asset
  Assets/ScriptableObject/Item/BATTLE_ITEM/Potion.asset
  Assets/Scripts/Character/Character.cs
  Assets/Scripts/Character/CharacterCollider.cs
  Assets/Scripts/Manager/Enum.cs
  Assets/Scripts/Manager/GameMng.cs
  Assets/Scripts/UI/Inventory/Inventory.cs
Labels: feature

#65 Feat: _target 설정 버그 수정, 보스 데미지 추가
  Assets/Scripts/Boss/Boss.cs
  Assets/Scripts/Boss/Wakgui/Bullet.cs
  Assets/Scripts/Boss/Wakgui/ChangeAction.cs
  Assets/Scripts/Boss/Wakgui/Marble.cs
  Assets/Scripts/Boss/Wakgui/Totem.cs
  Assets/Scripts/Boss/Wakgui/Wakgui.cs
  Assets/Scripts/Boss/Wakgui/Waves.cs
  Assets/Scripts/Character/Character.cs
  Assets/Scripts/Character/CharacterCollider.cs
  Assets/Scripts/Manager/StateMng.cs
Labels: bug, feature

#67 Feat: 보스 디버프 추가, 보스 패턴 버그 수정
  Assets/Prefab/UI/Buff_State.prefab
  Assets/Prefab/UI/RaidCanvas.prefab
  Assets/Prefab/UI/Tooltip.prefab
  Assets/Prefab/UI/Tooltip.prefab.meta
  Assets/Scenes/BossWakguiReadyScene.unity
  Assets/Scenes/BossWakguiScene.unity
  Assets/ScriptableObject/Boss/Wakgui.asset
  Assets/Scripts/Boss/Wakgui/Poo.cs
  Assets/Scripts/Boss/Wakgui/Wakgui.cs
  Assets/Scripts/Boss/Wakgui/Waves.cs
  Assets/Scripts/Character/CharacterState/Buff.cs
  Assets/Scripts/Manager/Scriptable/BossData.cs
  Assets/Scripts/Manager/StateMng.cs
Labels: bug, feature

#70 Change: 버그 수정 & 보스 타겟 Net.v_user로 변경
  Assets/Prefab/UI/RaidCanvas.prefab
  Assets/Scenes/BossWakguiScene.unity
  Assets/Scripts/Boss/BossCollider.cs
  Assets/Scripts/Boss/Wakgui/ChangeAction.cs
  Assets/Scripts/Boss/Wakgui/Wakgui.cs
  Assets/Scripts/Character/Character.cs
  Assets/Scripts/Character/CharacterState/Buff.cs
  Assets/Scripts/Manager/StateMng.cs
Labels: bug, duplicate

#78 Feat: 귀상어두 애니메이션 콜리더 2D -> 3D
  Assets/Animation/Boss/Wakgui/Jump.anim
  Assets/Animation/Boss/Wakgui/rush.anim
  Assets/Animation/Boss/Wakgui/slash.anim
  Assets/Animation/Boss/Wakgui/stap.anim
  Assets/Animation/Character/Attack.anim
  Assets/Animation/Character/Attack_1.anim
  Assets/Animation/Character/Attack_1.anim.meta
  Assets/Animation/Character/Character.controller
  Assets/Animation/Character/Dash_2.anim
  Assets/Animation/Character/Dash_2.anim.meta
  Assets/Animation/Character/Idle.anim
  Assets/Animation/Esther/Light_Wakgui/Viichan_Light.anim
  Assets/Animation/UI/Ping/Idle.anim
  Assets/Prefab/Boss/Wakgui/cristal_0.prefab
  Assets/Prefab/Boss/Wakgui/cristal_attack.prefab
  Assets/Prefab/Boss/Wakgui/wave.prefab
  Assets/Prefab/Character/Warrior.prefab
  Assets/Prefab/UI/Ping.prefab
  Assets/Scenes/BossWakguiReadyScene.unity
  Assets/Scenes/BossWakguiScene.unity
  Assets/Scenes/TempleScene.unity
  Assets/Scenes/_LoadScene.unity
  Assets/Scripts/Boss/BossCollider.cs
  Assets/Scripts/Boss/Wakgui/Bullet.cs
  Assets/Scripts/Boss/Wakgui/Cristal.cs
  Assets/Scripts/Boss/Wakgui/Wakgui.cs
  Assets/Scripts/Boss/Wakgui/Waves.cs
  Assets/Scripts/Character/Character.cs
  Assets/Scripts/Manager/EstherManager.cs
  Assets/Scripts/Manager/GameMng.cs
  Assets/Scripts/Manager/NetworkMng.cs
  Assets/Scripts/Manager/UIManager.cs
  Assets/Sprites/Map/Temple/temple_ground.png.meta
  ProjectSettings/TagManager.asset
Labels: feature
